- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - complementary [ref=e3]:
      - generic [ref=e4]: Sales
      - link "Inventory" [ref=e5] [cursor=pointer]:
        - /url: /pws/inventory
        - img [ref=e7]
        - generic [ref=e10]: Inventory
      - link "Offer Review" [ref=e11] [cursor=pointer]:
        - /url: /pws/offer-review
        - img [ref=e13]
        - generic [ref=e16]: Offer Review
      - link "RMA Review" [ref=e17] [cursor=pointer]:
        - /url: /pws/rma-review
        - img [ref=e19]
        - generic [ref=e23]: RMA Review
      - link "Pricing" [ref=e24] [cursor=pointer]:
        - /url: /pws/pricing
        - img [ref=e26]
        - generic [ref=e28]: Pricing
      - generic [ref=e29]: Buyers
      - link "Shop" [ref=e30] [cursor=pointer]:
        - /url: /pws/order
        - img [ref=e32]
        - generic [ref=e36]: Shop
      - link "Counters" [ref=e37] [cursor=pointer]:
        - /url: /pws/counter-offers
        - img [ref=e39]
        - generic [ref=e44]: Counters
      - link "Orders" [ref=e45] [cursor=pointer]:
        - /url: /pws/orders
        - img [ref=e47]
        - generic [ref=e50]: Orders
      - link "RMAs" [ref=e51] [cursor=pointer]:
        - /url: /pws/rma-requests
        - img [ref=e53]
        - generic [ref=e56]: RMAs
      - link "FAQ's" [ref=e57] [cursor=pointer]:
        - /url: /pws/faqs
        - img [ref=e59]
        - generic [ref=e62]: FAQ's
      - link "Grading" [ref=e63] [cursor=pointer]:
        - /url: /pws/grading
        - img [ref=e65]
        - generic [ref=e67]: Grading
    - generic [ref=e68]:
      - banner [ref=e69]:
        - generic [ref=e70]:
          - img "ecoATM" [ref=e71]
          - generic [ref=e72]: Premium Wholesale
          - button "Select buyer code" [ref=e84] [cursor=pointer]:
            - generic [ref=e85]: "001"
            - img [ref=e86]
        - button "User menu" [ref=e74] [cursor=pointer]:
          - img [ref=e75]
      - main [ref=e78]:
        - generic [ref=e80]:
          - generic [ref=e81]:
            - heading "Inventory" [level=1] [ref=e88]
            - generic [ref=e89]:
              - textbox "Search inventory..." [ref=e90]
              - img
            - button "Download" [ref=e91] [cursor=pointer]
          - generic [ref=e93]:
            - button "Functional Devices" [ref=e94] [cursor=pointer]
            - button "Untested Devices" [ref=e95] [cursor=pointer]
          - generic [ref=e96]:
            - table [ref=e98]:
              - rowgroup [ref=e99]:
                - row "SKU Category Brand Model Family Carrier Capacity Color Grade Price Avl. Qty" [ref=e100]:
                  - columnheader [ref=e101] [cursor=pointer]:
                    - checkbox [ref=e102]
                  - columnheader "SKU" [ref=e103] [cursor=pointer]
                  - columnheader "Category" [ref=e104] [cursor=pointer]
                  - columnheader "Brand" [ref=e105] [cursor=pointer]
                  - columnheader "Model Family" [ref=e106] [cursor=pointer]
                  - columnheader "Carrier" [ref=e107] [cursor=pointer]
                  - columnheader "Capacity" [ref=e108] [cursor=pointer]
                  - columnheader "Color" [ref=e109] [cursor=pointer]
                  - columnheader "Grade" [ref=e110] [cursor=pointer]
                  - columnheader "Price" [ref=e111] [cursor=pointer]
                  - columnheader "Avl. Qty" [ref=e112] [cursor=pointer]
                - row "All All All All All All All" [ref=e113]:
                  - columnheader [ref=e114]
                  - columnheader [ref=e115]:
                    - textbox [ref=e116]
                  - columnheader "All" [ref=e117]:
                    - combobox [ref=e118] [cursor=pointer]:
                      - option "All" [selected]
                      - option "Cell Phone"
                      - option "Tablet"
                  - columnheader "All" [ref=e119]:
                    - combobox [ref=e120] [cursor=pointer]:
                      - option "All" [selected]
                      - option "Apple"
                      - option "Asus"
                      - option "Blu"
                      - option "Google"
                      - option "Huawei"
                      - option "LG"
                      - option "Motorola"
                      - option "Nokia"
                      - option "OnePlus"
                      - option "Oppo"
                      - option "Realme"
                      - option "Samsung"
                      - option "Sony"
                      - option "Vivo"
                      - option "Xiaomi"
                      - option "ZTE"
                      - option "iPad"
                  - columnheader "All" [ref=e121]:
                    - combobox [ref=e122] [cursor=pointer]:
                      - option "All" [selected]
                      - option "Asus Rog Phone 6 128gb"
                      - option "Asus Rog Phone 6 256gb"
                      - option "Asus Rog Phone 6 2tb"
                      - option "Asus Rog Phone 6 8gb"
                      - option "Asus Rog Phone 7 10gb"
                      - option "Asus Rog Phone 7 2tb"
                      - option "Asus Rog Phone 7 5tb"
                      - option "Asus Rog Phone 8 256gb"
                      - option "Asus Rog Phone 8 2tb"
                      - option "Asus Rog Phone 8 64gb"
                      - option "Asus Zenfone 9 128gb"
                      - option "Asus Zenfone 9 1tb"
                      - option "Asus Zenfone 9 2tb"
                      - option "Asus Zenfone 9 32gb"
                      - option "Asus Zenfone 9 512gb"
                      - option "Cat S75 128gb"
                      - option "Cat S75 16gb"
                      - option "Cat S75 32gb"
                      - option "Edge+ (2023)"
                      - option "Fairphone 4 1tb"
                      - option "Fairphone 4 512gb"
                      - option "Fairphone 5 10gb"
                      - option "Fairphone 5 1tb"
                      - option "Fairphone 5 2tb"
                      - option "Find X3"
                      - option "Find X6"
                      - option "Galaxy Note10"
                      - option "Galaxy Note10+"
                      - option "Galaxy Note10+ 5G"
                      - option "Galaxy Note20 5G"
                      - option "Galaxy Note20 5g"
                      - option "Galaxy Note20 Ultra 5G"
                      - option "Galaxy Note9"
                      - option "Galaxy S10"
                      - option "Galaxy S10 5G"
                      - option "Galaxy S10+"
                      - option "Galaxy S10e"
                      - option "Galaxy S20"
                      - option "Galaxy S20 2tb"
                      - option "Galaxy S20 512gb"
                      - option "Galaxy S20 FE 5G"
                      - option "Galaxy S20 Fe 10gb"
                      - option "Galaxy S20 Fe 2tb"
                      - option "Galaxy S20 Fe 8gb"
                      - option "Galaxy S20 Ultra"
                      - option "Galaxy S20 Ultra 4gb"
                      - option "Galaxy S20 Ultra 512gb"
                      - option "Galaxy S20 Ultra 64gb"
                      - option "Galaxy S20 Ultra 8gb"
                      - option "Galaxy S20+"
                      - option "Galaxy S20+ 16gb"
                      - option "Galaxy S20+ 1tb"
                      - option "Galaxy S21"
                      - option "Galaxy S21 5G"
                      - option "Galaxy S21 FE 5G"
                      - option "Galaxy S21 Fe 128gb"
                      - option "Galaxy S21 Fe 4gb"
                      - option "Galaxy S21 Ultra"
                      - option "Galaxy S21 Ultra 16gb"
                      - option "Galaxy S21 Ultra 32gb"
                      - option "Galaxy S21 Ultra 5G"
                      - option "Galaxy S21+"
                      - option "Galaxy S21+ 256gb"
                      - option "Galaxy S21+ 5G"
                      - option "Galaxy S22 1tb"
                      - option "Galaxy S22 32gb"
                      - option "Galaxy S22 4gb"
                      - option "Galaxy S22 512gb"
                      - option "Galaxy S22 5G"
                      - option "Galaxy S22 Ultra"
                      - option "Galaxy S22 Ultra 10gb"
                      - option "Galaxy S22 Ultra 128gb"
                      - option "Galaxy S22 Ultra 16gb"
                      - option "Galaxy S22 Ultra 4gb"
                      - option "Galaxy S22 Ultra 5G"
                      - option "Galaxy S22+ 10gb"
                      - option "Galaxy S22+ 16gb"
                      - option "Galaxy S22+ 5G"
                      - option "Galaxy S23"
                      - option "Galaxy S23 10gb"
                      - option "Galaxy S23 16gb"
                      - option "Galaxy S23 256gb"
                      - option "Galaxy S23 2tb"
                      - option "Galaxy S23 32gb"
                      - option "Galaxy S23 4gb"
                      - option "Galaxy S23 512gb"
                      - option "Galaxy S23 5tb"
                      - option "Galaxy S23 64gb"
                      - option "Galaxy S23 8gb"
                      - option "Galaxy S23 FE"
                      - option "Galaxy S23 Fe 8gb"
                      - option "Galaxy S23 Ultra"
                      - option "Galaxy S23+"
                      - option "Galaxy S23+ 128gb"
                      - option "Galaxy S23+ 256gb"
                      - option "Galaxy S23+ 512gb"
                      - option "Galaxy S23+ 8gb"
                      - option "Galaxy S24"
                      - option "Galaxy S24 128gb"
                      - option "Galaxy S24 16gb"
                      - option "Galaxy S24 FE"
                      - option "Galaxy S24 Ultra"
                      - option "Galaxy S24 Ultra 16gb"
                      - option "Galaxy S24 Ultra 4gb"
                      - option "Galaxy S24+"
                      - option "Galaxy S25"
                      - option "Galaxy S25 Edge"
                      - option "Galaxy S25 Ultra"
                      - option "Galaxy S25+"
                      - option "Galaxy S26"
                      - option "Galaxy S26 Ultra"
                      - option "Galaxy S26+"
                      - option "Galaxy S6"
                      - option "Galaxy S6 Edge"
                      - option "Galaxy S7"
                      - option "Galaxy S8"
                      - option "Galaxy S9"
                      - option "Galaxy S9+"
                      - option "Galaxy Tab S10 Ultra"
                      - option "Galaxy Tab S10+"
                      - option "Galaxy Z Flip 3 2tb"
                      - option "Galaxy Z Flip 4 4gb"
                      - option "Galaxy Z Flip 5 2tb"
                      - option "Galaxy Z Flip3 5G"
                      - option "Galaxy Z Flip4"
                      - option "Galaxy Z Flip5"
                      - option "Galaxy Z Flip6"
                      - option "Galaxy Z Fold 4 1tb"
                      - option "Galaxy Z Fold 4 256gb"
                      - option "Galaxy Z Fold 5 256gb"
                      - option "Galaxy Z Fold3 5G"
                      - option "Galaxy Z Fold4"
                      - option "Galaxy Z Fold5"
                      - option "Galaxy Z Fold6"
                      - option "Google Pixel 10 Pro Xl"
                      - option "Honor 100 10gb"
                      - option "Honor 100 16gb"
                      - option "Honor 100 512gb"
                      - option "Honor 90 128gb"
                      - option "Honor 90 16gb"
                      - option "Honor 90 4gb"
                      - option "Honor 90 64gb"
                      - option "Honor Magic 5 16gb"
                      - option "Honor Magic 5 256gb"
                      - option "Honor Magic 6 Pro 16gb"
                      - option "Huawei Mate 10"
                      - option "Huawei Mate 50 Pro 16gb"
                      - option "Huawei Mate 50 Pro 256gb"
                      - option "Huawei Mate 50 Pro 5tb"
                      - option "Huawei Mate 60 Pro 10gb"
                      - option "Huawei Mate 60 Pro 2tb"
                      - option "Huawei Mate Xs 2 10gb"
                      - option "Huawei Mate Xs 2 32gb"
                      - option "Huawei P40 128gb"
                      - option "Huawei P40 2tb"
                      - option "Huawei P40 32gb"
                      - option "Huawei P40 5tb"
                      - option "Huawei P40 8gb"
                      - option "Huawei P40 Pro 1tb"
                      - option "Huawei P60 Pro 2tb"
                      - option "Huawei P9"
                      - option "Iqoo 11 128gb"
                      - option "Iqoo 11 2tb"
                      - option "Iqoo 11 8gb"
                      - option "Iqoo 12 16gb"
                      - option "Iqoo 12 2tb"
                      - option "Iqoo 12 32gb"
                      - option "Iqoo 12 5tb"
                      - option "Iqoo 12 64gb"
                      - option "Iqoo 12 8gb"
                      - option "Kyocera Duraforce Pro 3 256gb"
                      - option "Kyocera Duraforce Pro 3 32gb"
                      - option "Lg Velvet 4gb"
                      - option "Lg Velvet 512gb"
                      - option "Lg Velvet 8gb"
                      - option "Mate 20"
                      - option "Mate 30"
                      - option "Mate 40"
                      - option "Mi 11"
                      - option "Mi 12"
                      - option "Mi 9 Pro"
                      - option "Mi 9t"
                      - option "Moto Edge"
                      - option "Moto Edge+"
                      - option "Moto G Power 2024 2tb"
                      - option "Moto G Stylus 2024 16gb"
                      - option "Moto G Stylus 2024 5tb"
                      - option "Moto G Stylus 2024 8gb"
                      - option "Moto Z"
                      - option "Moto Z2 Force"
                      - option "Motorola Edge 30 Pro 32gb"
                      - option "Motorola Edge 30 Pro 64gb"
                      - option "Motorola Edge 40 16gb"
                      - option "Motorola Edge 40 4gb"
                      - option "Nokia X30 5g 4gb"
                      - option "Nokia X30 5g 64gb"
                      - option "Nokia Xr21 5tb"
                      - option "Nubia Z50 Ultra 128gb"
                      - option "Nubia Z50 Ultra 2tb"
                      - option "Nubia Z50 Ultra 32gb"
                      - option "Nubia Z60 Ultra 5tb"
                      - option "Oneplus 10 Pro"
                      - option "Oneplus 10 Pro 1tb"
                      - option "Oneplus 10 Pro 256gb"
                      - option "Oneplus 10 Pro 2tb"
                      - option "Oneplus 10t 10gb"
                      - option "Oneplus 10t 16gb"
                      - option "Oneplus 10t 256gb"
                      - option "Oneplus 10t 512gb"
                      - option "Oneplus 11"
                      - option "Oneplus 11 128gb"
                      - option "Oneplus 11 8gb"
                      - option "Oneplus 11r 1tb"
                      - option "Oneplus 12"
                      - option "Oneplus 12 128gb"
                      - option "Oneplus 12 1tb"
                      - option "Oneplus 12 256gb"
                      - option "Oneplus 12 2tb"
                      - option "Oneplus 12 32gb"
                      - option "Oneplus 12 4gb"
                      - option "Oneplus 12 512gb"
                      - option "Oneplus 12 5tb"
                      - option "Oneplus 12 64gb"
                      - option "Oneplus 12 8gb"
                      - option "Oneplus 12r 5tb"
                      - option "Oneplus 12r 64gb"
                      - option "Oneplus 13"
                      - option "Oneplus 15"
                      - option "Oneplus 2"
                      - option "Oneplus 3"
                      - option "Oneplus 3t"
                      - option "Oneplus 5"
                      - option "Oneplus 6"
                      - option "Oneplus 6t"
                      - option "Oneplus 7"
                      - option "Oneplus 7 Pro"
                      - option "Oneplus 7t Pro"
                      - option "Oneplus 8"
                      - option "Oneplus 8 4gb"
                      - option "Oneplus 8 512gb"
                      - option "Oneplus 8 Pro"
                      - option "Oneplus 8 Pro 16gb"
                      - option "Oneplus 8t 128gb"
                      - option "Oneplus 9 2tb"
                      - option "Oneplus 9 4gb"
                      - option "Oneplus 9 Pro"
                      - option "Oneplus 9 Pro 256gb"
                      - option "Oneplus 9 Pro 32gb"
                      - option "Oneplus 9r 4gb"
                      - option "Oneplus Nord 2 4gb"
                      - option "Oneplus Nord Ce 5g 2tb"
                      - option "Oppo Find X"
                      - option "Oppo Find X3 Pro 128gb"
                      - option "Oppo Find X3 Pro 5tb"
                      - option "Oppo Find X5 Pro 2tb"
                      - option "Oppo Find X5 Pro 5tb"
                      - option "Oppo Find X6 Pro 8gb"
                      - option "Oppo Find X7 Ultra 16gb"
                      - option "Oppo Find X7 Ultra 1tb"
                      - option "Oppo Reno 10"
                      - option "Oppo Reno 10 128gb"
                      - option "Oppo Reno 10 32gb"
                      - option "Oppo Reno 10 64gb"
                      - option "Oppo Reno 11 128gb"
                      - option "Oppo Reno 11 1tb"
                      - option "Oppo Reno 9 128gb"
                      - option "Oppo Reno 9 1tb"
                      - option "Oppo Reno 9 4gb"
                      - option "P30"
                      - option "P50"
                      - option "Palm Phone (2019) 16gb"
                      - option "Palm Phone (2019) 2tb"
                      - option "Palm Phone (2019) 32gb"
                      - option "Palm Phone (2019) 8gb"
                      - option "Pixel"
                      - option "Pixel 10"
                      - option "Pixel 10 Pro"
                      - option "Pixel 2 Xl"
                      - option "Pixel 3"
                      - option "Pixel 3 Xl"
                      - option "Pixel 4"
                      - option "Pixel 4 16gb"
                      - option "Pixel 4 512gb"
                      - option "Pixel 4 XL"
                      - option "Pixel 4 Xl 128gb"
                      - option "Pixel 4 Xl 1tb"
                      - option "Pixel 4a"
                      - option "Pixel 4a 2tb"
                      - option "Pixel 4a 4gb"
                      - option "Pixel 4a 5tb"
                      - option "Pixel 5"
                      - option "Pixel 5a"
                      - option "Pixel 5a 128gb"
                      - option "Pixel 5a 32gb"
                      - option "Pixel 5a 512gb"
                      - option "Pixel 5a 8gb"
                      - option "Pixel 6"
                      - option "Pixel 6 32gb"
                      - option "Pixel 6 5tb"
                      - option "Pixel 6 Pro"
                      - option "Pixel 6 Pro 16gb"
                      - option "Pixel 6 Pro 32gb"
                      - option "Pixel 6 Pro 8gb"
                      - option "Pixel 6a"
                      - option "Pixel 6a 1tb"
                      - option "Pixel 6a 5tb"
                      - option "Pixel 6a 8gb"
                      - option "Pixel 7"
                      - option "Pixel 7 128gb"
                      - option "Pixel 7 1tb"
                      - option "Pixel 7 5tb"
                      - option "Pixel 7 Pro"
                      - option "Pixel 7 Pro 256gb"
                      - option "Pixel 7 Pro 2tb"
                      - option "Pixel 7a"
                      - option "Pixel 7a 1tb"
                      - option "Pixel 7a 2tb"
                      - option "Pixel 7a 64gb"
                      - option "Pixel 7a 8gb"
                      - option "Pixel 8"
                      - option "Pixel 8 1tb"
                      - option "Pixel 8 5tb"
                      - option "Pixel 8 Pro"
                      - option "Pixel 8 Pro 10gb"
                      - option "Pixel 8 Pro 128gb"
                      - option "Pixel 8 Pro 256gb"
                      - option "Pixel 8 Pro 2tb"
                      - option "Pixel 8 Pro 32gb"
                      - option "Pixel 8 Pro 4gb"
                      - option "Pixel 8 Pro 5tb"
                      - option "Pixel 8 Pro 8gb"
                      - option "Pixel 8a"
                      - option "Pixel 8a 10gb"
                      - option "Pixel 9"
                      - option "Pixel 9 Pro"
                      - option "Pixel 9 Pro Fold"
                      - option "Pixel 9 Pro XL"
                      - option "Pixel 9a"
                      - option "Pixel Fold"
                      - option "Pixel Fold 128gb"
                      - option "Pixel Fold 4gb"
                      - option "Pixel Fold 512gb"
                      - option "Pixel Xl"
                      - option "Poco F4 2tb"
                      - option "Poco F5 2tb"
                      - option "Poco F6 10gb"
                      - option "Poco F6 64gb"
                      - option "Poco F6 8gb"
                      - option "Poco X5 Pro 1tb"
                      - option "Poco X6 Pro 1tb"
                      - option "Poco X6 Pro 64gb"
                      - option "Razr 2023 10gb"
                      - option "Razr 2023 16gb"
                      - option "Razr 2023 256gb"
                      - option "Razr 2023 5tb"
                      - option "Razr 2023 64gb"
                      - option "Razr 2024 10gb"
                      - option "Realme 12 Pro 2tb"
                      - option "Realme Gt 2 Pro 512gb"
                      - option "Realme Gt 3 32gb"
                      - option "Realme Gt 3 4gb"
                      - option "Realme Gt 3 5tb"
                      - option "Realme Gt 5 128gb"
                      - option "Red Magic 9 Pro 1tb"
                      - option "Redmi Note 11 512gb"
                      - option "Redmi Note 11 5tb"
                      - option "Redmi Note 12 128gb"
                      - option "Redmi Note 12 256gb"
                      - option "Redmi Note 12 8gb"
                      - option "Redmi Note 13 8gb"
                      - option "Rog Phone 3"
                      - option "Rog Phone 5"
                      - option "Rog Phone 6"
                      - option "Rog Phone 6d"
                      - option "Shiftphone 8 2tb"
                      - option "Sony Xperia 1"
                      - option "Sony Xperia 1 Iii 8gb"
                      - option "Sony Xperia 1 Iv 10gb"
                      - option "Sony Xperia 1 Iv 32gb"
                      - option "Sony Xperia 1 Iv 64gb"
                      - option "Sony Xperia 1 V 10gb"
                      - option "Sony Xperia 5 V 1tb"
                      - option "Sony Xperia 5 V 2tb"
                      - option "Vivo X100 4gb"
                      - option "Vivo X100 512gb"
                      - option "Vivo X100 Pro 10gb"
                      - option "Vivo X90 Pro 16gb"
                      - option "Vivo X90 Pro 4gb"
                      - option "Xiaomi 11 2tb"
                      - option "Xiaomi 11t 8gb"
                      - option "Xiaomi 11t Pro 2tb"
                      - option "Xiaomi 12 10gb"
                      - option "Xiaomi 12 2tb"
                      - option "Xiaomi 12 Pro 2tb"
                      - option "Xiaomi 12 Pro 4gb"
                      - option "Xiaomi 12 Pro 5tb"
                      - option "Xiaomi 12 Pro 64gb"
                      - option "Xiaomi 12t 16gb"
                      - option "Xiaomi 12t 1tb"
                      - option "Xiaomi 12t 64gb"
                      - option "Xiaomi 12t Pro 2tb"
                      - option "Xiaomi 13"
                      - option "Xiaomi 13 16gb"
                      - option "Xiaomi 13 2tb"
                      - option "Xiaomi 13 32gb"
                      - option "Xiaomi 13 Pro 10gb"
                      - option "Xiaomi 13t 16gb"
                      - option "Xiaomi 13t 1tb"
                      - option "Xiaomi 13t 5tb"
                      - option "Xiaomi 13t Pro 16gb"
                      - option "Xiaomi 13t Pro 8gb"
                      - option "Xiaomi 14 128gb"
                      - option "Xiaomi 14 16gb"
                      - option "Xiaomi 14 1tb"
                      - option "Xiaomi 14 2tb"
                      - option "Xiaomi 14 32gb"
                      - option "Xiaomi 14 4gb"
                      - option "Xiaomi 14 512gb"
                      - option "Xiaomi 14 5tb"
                      - option "Xiaomi 14 64gb"
                      - option "Xiaomi 14 8gb"
                      - option "Xiaomi 14 Pro 5tb"
                      - option "Xiaomi 15"
                      - option "Xiaomi 15 Pro"
                      - option "Xiaomi Mi 5"
                      - option "Xperia 1 Ii"
                      - option "Xperia 1 Iii"
                      - option "Xperia 1 Iv"
                      - option "Zte Axon 40 Ultra 32gb"
                      - option "iPad (10th generation)"
                      - option "iPad (5th generation)"
                      - option "iPad (6th generation)"
                      - option "iPad (7th generation)"
                      - option "iPad (8th generation)"
                      - option "iPad (9th generation)"
                      - option "iPad Air"
                      - option "iPad Air (3rd generation)"
                      - option "iPad Air (4th generation)"
                      - option "iPad Air (5th generation)"
                      - option "iPad Air 13-inch (M2)"
                      - option "iPad Air 2"
                      - option "iPad Pro (10.5-inch)"
                      - option "iPad Pro (12.9-inch)"
                      - option "iPad Pro (9.7-inch)"
                      - option "iPad Pro 11-inch"
                      - option "iPad Pro 11-inch (2nd generation)"
                      - option "iPad Pro 11-inch (3rd generation)"
                      - option "iPad Pro 11-inch (4th generation)"
                      - option "iPad Pro 12.9-inch (3rd generation)"
                      - option "iPad Pro 12.9-inch (4th generation)"
                      - option "iPad Pro 12.9-inch (5th generation)"
                      - option "iPad Pro 12.9-inch (6th generation)"
                      - option "iPad mini"
                      - option "iPad mini (5th generation)"
                      - option "iPad mini (6th generation)"
                      - option "iPad mini 4"
                      - option "iPhone 11"
                      - option "iPhone 11 1tb"
                      - option "iPhone 11 512gb"
                      - option "iPhone 11 5tb"
                      - option "iPhone 11 Pro"
                      - option "iPhone 11 Pro 512gb"
                      - option "iPhone 11 Pro Max"
                      - option "iPhone 11 Pro Max 5tb"
                      - option "iPhone 12"
                      - option "iPhone 12 128gb"
                      - option "iPhone 12 Mini"
                      - option "iPhone 12 Mini 2tb"
                      - option "iPhone 12 Mini 32gb"
                      - option "iPhone 12 Mini 5tb"
                      - option "iPhone 12 Pro"
                      - option "iPhone 12 Pro 10gb"
                      - option "iPhone 12 Pro Max"
                      - option "iPhone 12 Pro Max 1tb"
                      - option "iPhone 12 Pro Max 2tb"
                      - option "iPhone 13"
                      - option "iPhone 13 10gb"
                      - option "iPhone 13 16gb"
                      - option "iPhone 13 1tb"
                      - option "iPhone 13 256gb"
                      - option "iPhone 13 32gb"
                      - option "iPhone 13 512gb"
                      - option "iPhone 13 Mini"
                      - option "iPhone 13 Mini 10gb"
                      - option "iPhone 13 Mini 256gb"
                      - option "iPhone 13 Mini 32gb"
                      - option "iPhone 13 Mini 512gb"
                      - option "iPhone 13 Mini 64gb"
                      - option "iPhone 13 Pro"
                      - option "iPhone 13 Pro 10gb"
                      - option "iPhone 13 Pro 16gb"
                      - option "iPhone 13 Pro 1tb"
                      - option "iPhone 13 Pro 256gb"
                      - option "iPhone 13 Pro 512gb"
                      - option "iPhone 13 Pro 8gb"
                      - option "iPhone 13 Pro Max"
                      - option "iPhone 13 Pro Max 1tb"
                      - option "iPhone 13 Pro Max 256gb"
                      - option "iPhone 13 Pro Max 2tb"
                      - option "iPhone 13 Pro Max 512gb"
                      - option "iPhone 137"
                      - option "iPhone 14"
                      - option "iPhone 14 128gb"
                      - option "iPhone 14 16gb"
                      - option "iPhone 14 256gb"
                      - option "iPhone 14 2tb"
                      - option "iPhone 14 512gb"
                      - option "iPhone 14 5tb"
                      - option "iPhone 14 64gb"
                      - option "iPhone 14 Plus"
                      - option "iPhone 14 Plus 10gb"
                      - option "iPhone 14 Plus 256gb"
                      - option "iPhone 14 Plus 2tb"
                      - option "iPhone 14 Plus 512gb"
                      - option "iPhone 14 Plus 64gb"
                      - option "iPhone 14 Plus 8gb"
                      - option "iPhone 14 Pro"
                      - option "iPhone 14 Pro 128gb"
                      - option "iPhone 14 Pro 16gb"
                      - option "iPhone 14 Pro 1tb"
                      - option "iPhone 14 Pro 256gb"
                      - option "iPhone 14 Pro 512gb"
                      - option "iPhone 14 Pro 5tb"
                      - option "iPhone 14 Pro Max"
                      - option "iPhone 14 Pro Max 16gb"
                      - option "iPhone 14 Pro Max 1tb"
                      - option "iPhone 14 Pro Max 256gb"
                      - option "iPhone 14 Pro Max 512gb"
                      - option "iPhone 15"
                      - option "iPhone 15 4gb"
                      - option "iPhone 15 Plus"
                      - option "iPhone 15 Plus 64gb"
                      - option "iPhone 15 Pro"
                      - option "iPhone 15 Pro 256gb"
                      - option "iPhone 15 Pro 32gb"
                      - option "iPhone 15 Pro Max"
                      - option "iPhone 15 Pro Max 10gb"
                      - option "iPhone 15 Pro Max 128gb"
                      - option "iPhone 15 Pro Max 1tb"
                      - option "iPhone 15 Pro Max 256gb"
                      - option "iPhone 15 Pro Max 32gb"
                      - option "iPhone 15 Pro Max 4gb"
                      - option "iPhone 15 Pro Max 512gb"
                      - option "iPhone 15 Pro Max 5tb"
                      - option "iPhone 16"
                      - option "iPhone 16 Plus"
                      - option "iPhone 16 Pro"
                      - option "iPhone 16 Pro Max"
                      - option "iPhone 16e"
                      - option "iPhone 17 Pro"
                      - option "iPhone 17 Pro Max"
                      - option "iPhone 241"
                      - option "iPhone 314"
                      - option "iPhone 5"
                      - option "iPhone 676"
                      - option "iPhone 6s Plus"
                      - option "iPhone 8 5tb"
                      - option "iPhone 8 Plus"
                      - option "iPhone 817"
                      - option "iPhone SE (2nd generation)"
                      - option "iPhone SE (3rd generation)"
                      - option "iPhone Se (2022) 10gb"
                      - option "iPhone Se (2022) 32gb"
                      - option "iPhone Se (2022) 64gb"
                      - option "iPhone X"
                      - option "iPhone X 10gb"
                      - option "iPhone XR"
                      - option "iPhone XS"
                      - option "iPhone XS Max"
                      - option "iPhone Xr"
                      - option "iPhone Xr 256gb"
                      - option "iPhone Xr 512gb"
                      - option "iPhone Xr 5tb"
                      - option "iPhone Xr 8gb"
                      - option "iPhone Xs 64gb"
                      - option "iPhone Xs Max"
                      - option "iPhone Xs Max 128gb"
                      - option "iPhone Xs Max 16gb"
                      - option "iPhone Xs Max 256gb"
                      - option "iPhone Xs Max 2tb"
                      - option "iPhone Xs Max 32gb"
                      - option "iPhone Xs Max 8gb"
                      - option "iphone 11"
                  - columnheader "All" [ref=e123]:
                    - combobox [ref=e124] [cursor=pointer]:
                      - option "All" [selected]
                  - columnheader "All" [ref=e125]:
                    - combobox [ref=e126] [cursor=pointer]:
                      - option "All" [selected]
                      - option "(3rd generation) 256GB (Unlocked)"
                      - option "(3rd generation) 256GB (WiFi)"
                      - option "(3rd generation) 64GB (Unlocked)"
                      - option "(3rd generation) 64GB (WiFi)"
                      - option "(4th generation) 256GB (Unlocked)"
                      - option "(4th generation) 256GB (WiFi)"
                      - option "(4th generation) 64GB (Unlocked)"
                      - option "(4th generation) 64GB (WiFi)"
                      - option "(5th generation) 256GB (Unlocked)"
                      - option "(5th generation) 256GB (WiFi)"
                      - option "(5th generation) 64GB (Unlocked)"
                      - option "(5th generation) 64GB (WiFi)"
                      - option "(6th generation) 256GB (Unlocked)"
                      - option "(6th generation) 256GB (WiFi)"
                      - option "(6th generation) 64GB (Unlocked)"
                      - option "(6th generation) 64GB (WiFi)"
                      - option "(A17 Pro) 128GB (Unlocked)"
                      - option "(A17 Pro) 128GB (WiFi)"
                      - option "(A17 Pro) 256GB (Unlocked)"
                      - option "(A17 Pro) 256GB (WiFi)"
                      - option "(A17 Pro) 512GB (Unlocked)"
                      - option "(A17 Pro) 512GB (WiFi)"
                      - option "10GB"
                      - option "11-inch (2nd generation) 128GB (Unlocked)"
                      - option "11-inch (2nd generation) 128GB (WiFi)"
                      - option "11-inch (2nd generation) 1TB (Unlocked)"
                      - option "11-inch (2nd generation) 1TB (WiFi)"
                      - option "11-inch (2nd generation) 256GB (Unlocked)"
                      - option "11-inch (2nd generation) 256GB (WiFi)"
                      - option "11-inch (2nd generation) 512GB (Unlocked)"
                      - option "11-inch (2nd generation) 512GB (WiFi)"
                      - option "11-inch (3rd generation) 128GB (Unlocked)"
                      - option "11-inch (3rd generation) 128GB (WiFi)"
                      - option "11-inch (3rd generation) 1TB (Unlocked)"
                      - option "11-inch (3rd generation) 1TB (WiFi)"
                      - option "11-inch (3rd generation) 256GB (Unlocked)"
                      - option "11-inch (3rd generation) 256GB (WiFi)"
                      - option "11-inch (3rd generation) 2TB (Unlocked)"
                      - option "11-inch (3rd generation) 2TB (WiFi)"
                      - option "11-inch (3rd generation) 512GB (Unlocked)"
                      - option "11-inch (3rd generation) 512GB (WiFi)"
                      - option "11-inch (4th generation) 128GB (Unlocked)"
                      - option "11-inch (4th generation) 128GB (WiFi)"
                      - option "11-inch (4th generation) 1TB (Unlocked)"
                      - option "11-inch (4th generation) 1TB (WiFi)"
                      - option "11-inch (4th generation) 256GB (Unlocked)"
                      - option "11-inch (4th generation) 256GB (WiFi)"
                      - option "11-inch (4th generation) 2TB (Unlocked)"
                      - option "11-inch (4th generation) 2TB (WiFi)"
                      - option "11-inch (4th generation) 512GB (Unlocked)"
                      - option "11-inch (4th generation) 512GB (WiFi)"
                      - option "11-inch (M2) 128GB (Unlocked)"
                      - option "11-inch (M2) 128GB (WiFi)"
                      - option "11-inch (M2) 1TB (Unlocked)"
                      - option "11-inch (M2) 1TB (WiFi)"
                      - option "11-inch (M2) 256GB (Unlocked)"
                      - option "11-inch (M2) 256GB (WiFi)"
                      - option "11-inch (M2) 512GB (Unlocked)"
                      - option "11-inch (M2) 512GB (WiFi)"
                      - option "11-inch (M3) 128GB (Unlocked)"
                      - option "11-inch (M3) 128GB (WiFi)"
                      - option "11-inch (M3) 1TB (Unlocked)"
                      - option "11-inch (M3) 1TB (WiFi)"
                      - option "11-inch (M3) 256GB (Unlocked)"
                      - option "11-inch (M3) 256GB (WiFi)"
                      - option "11-inch (M3) 512GB (Unlocked)"
                      - option "11-inch (M3) 512GB (WiFi)"
                      - option "11-inch (M4) 1TB (Unlocked)"
                      - option "11-inch (M4) 1TB (WiFi)"
                      - option "11-inch (M4) 256GB (Unlocked)"
                      - option "11-inch (M4) 256GB (WiFi)"
                      - option "11-inch (M4) 2TB (Unlocked)"
                      - option "11-inch (M4) 2TB (WiFi)"
                      - option "11-inch (M4) 512GB (Unlocked)"
                      - option "11-inch (M4) 512GB (WiFi)"
                      - option "11-inch 1TB (Unlocked)"
                      - option "11-inch 1TB (WiFi)"
                      - option "11-inch 256GB (Unlocked)"
                      - option "11-inch 256GB (WiFi)"
                      - option "11-inch 512GB (Unlocked)"
                      - option "11-inch 512GB (WiFi)"
                      - option "11-inch 64GB (Unlocked)"
                      - option "11-inch 64GB (WiFi)"
                      - option "12"
                      - option "128GB"
                      - option "128GB (Unlocked)"
                      - option "128GB (WiFi)"
                      - option "13-inch (M2) 128GB (Unlocked)"
                      - option "13-inch (M2) 128GB (WiFi)"
                      - option "13-inch (M2) 256GB (WiFi)"
                      - option "13-inch (M3) 128GB (Unlocked)"
                      - option "13-inch (M3) 128GB (WiFi)"
                      - option "13-inch (M3) 1TB (Unlocked)"
                      - option "13-inch (M3) 1TB (WiFi)"
                      - option "13-inch (M3) 256GB (Unlocked)"
                      - option "13-inch (M3) 256GB (WiFi)"
                      - option "13-inch (M3) 512GB (Unlocked)"
                      - option "13-inch (M3) 512GB (WiFi)"
                      - option "13-inch (M4) 1TB (Unlocked)"
                      - option "13-inch (M4) 1TB (WiFi)"
                      - option "13-inch (M4) 256GB (Unlocked)"
                      - option "13-inch (M4) 256GB (WiFi)"
                      - option "13-inch (M4) 2TB (Unlocked)"
                      - option "13-inch (M4) 2TB (WiFi)"
                      - option "13-inch (M4) 512GB (Unlocked)"
                      - option "13-inch (M4) 512GB (WiFi)"
                      - option "16GB"
                      - option "1TB"
                      - option "256B"
                      - option "256GB"
                      - option "256GB (Unlocked)"
                      - option "256GB (WiFi)"
                      - option "2TB"
                      - option "32GB"
                      - option "4GB"
                      - option "512GB"
                      - option "512GB (Unlocked)"
                      - option "512GB (WiFi)"
                      - option "5TB"
                      - option "64GB"
                      - option "8GB"
                      - option "IPHONE"
                      - option "Wifi"
                      - option "generation) 128GB (Unlocked)"
                      - option "generation) 128GB (WiFi)"
                      - option "generation) 256GB (Unlocked)"
                      - option "generation) 256GB (WiFi)"
                      - option "generation) 32GB (Unlocked)"
                      - option "generation) 32GB (WiFi)"
                      - option "generation) 64GB (Unlocked)"
                      - option "generation) 64GB (WiFi)"
                  - columnheader "All" [ref=e127]:
                    - combobox [ref=e128] [cursor=pointer]:
                      - option "All" [selected]
                      - option "(Product)Red"
                      - option "(product)red"
                      - option "128gb"
                      - option "1tb"
                      - option "20 Count Case Pack"
                      - option "256gb"
                      - option "2tb"
                      - option "512gb"
                      - option "64gb"
                      - option ":Pink"
                      - option "Aloe"
                      - option "Alpine Green"
                      - option "Alpine White"
                      - option "Amber Yellow"
                      - option "Aura Black"
                      - option "Aura Blue"
                      - option "Aura Glow"
                      - option "Aura Pink"
                      - option "Aura Red"
                      - option "Aura White"
                      - option "Barely Blue"
                      - option "Bay"
                      - option "Beige"
                      - option "Black"
                      - option "Black Coral"
                      - option "Black Titanium"
                      - option "Black/blue"
                      - option "Blue"
                      - option "Blue Black"
                      - option "Blue Titanium"
                      - option "Blueblack"
                      - option "Bora Purple"
                      - option "Burgundy"
                      - option "Canary Yellow"
                      - option "Cardinal Red"
                      - option "Ceramic Black"
                      - option "Ceramic White"
                      - option "Chalk"
                      - option "Charcoal"
                      - option "Clearly White"
                      - option "Cloud Blue"
                      - option "Cloud Lavender"
                      - option "Cloud Mint"
                      - option "Cloud Navy"
                      - option "Cloud Orange"
                      - option "Cloud Pink"
                      - option "Cloud Red"
                      - option "Cloud White"
                      - option "Cloudy White"
                      - option "Cobalt Violet"
                      - option "Coral"
                      - option "Coralred"
                      - option "Cosmic Black"
                      - option "Cosmic Grey"
                      - option "Cream"
                      - option "Crown Silver"
                      - option "Deep Purple"
                      - option "Desert Titanium"
                      - option "Flamingo Pink"
                      - option "Glacier Blue"
                      - option "Gold"
                      - option "Graphite"
                      - option "Gray"
                      - option "Graygreen"
                      - option "Green"
                      - option "Grey"
                      - option "Hazel"
                      - option "Icy Blue"
                      - option "Indigo"
                      - option "Infinite Black"
                      - option "Iris"
                      - option "Jade Green"
                      - option "Just Black"
                      - option "Khaki"
                      - option "Kinda Coral"
                      - option "Lavender"
                      - option "Lavender Purple"
                      - option "Lemongrass"
                      - option "Light Gray"
                      - option "Lime"
                      - option "Majestic Black"
                      - option "Marble Grey"
                      - option "Metallic Copper"
                      - option "Midnight"
                      - option "Midnight Black"
                      - option "Midnight Green"
                      - option "Midnightgreen"
                      - option "Mink Green"
                      - option "Mint"
                      - option "Mint Navy"
                      - option "Moonstone"
                      - option "Moonstone Gray"
                      - option "Mostly Black"
                      - option "Mystic Black"
                      - option "Mystic Blue"
                      - option "Mystic Bronze"
                      - option "Mystic Gray"
                      - option "Mystic Green"
                      - option "Mystic Red"
                      - option "Mystic White"
                      - option "Na"
                      - option "Natural Black"
                      - option "Natural Blue"
                      - option "Natural Coral"
                      - option "Natural Gray"
                      - option "Natural Greenish"
                      - option "Natural Reddish"
                      - option "Natural Titanium"
                      - option "Navy"
                      - option "Obsidian"
                      - option "Ocean Blue"
                      - option "Oh So Orange"
                      - option "Olive"
                      - option "Onyx Black"
                      - option "Pacific Blue"
                      - option "Palegreen"
                      - option "Peach"
                      - option "Peony"
                      - option "Phantom Black"
                      - option "Phantom Brown"
                      - option "Phantom Gold"
                      - option "Phantom Gray"
                      - option "Phantom Green"
                      - option "Phantom Navy"
                      - option "Phantom Pink"
                      - option "Phantom Red"
                      - option "Phantom Silver"
                      - option "Phantom Titanium"
                      - option "Phantom Violet"
                      - option "Phantom White"
                      - option "Pink"
                      - option "Pink Gold"
                      - option "Pinkgold"
                      - option "Platinum Silver"
                      - option "Porcelain"
                      - option "Prism Black"
                      - option "Prism Blue"
                      - option "Prism Green"
                      - option "Prism White"
                      - option "Pure White"
                      - option "Purple"
                      - option "Red"
                      - option "Rose"
                      - option "Rose Gold"
                      - option "Rose Quartz"
                      - option "Royal Gold"
                      - option "Sage"
                      - option "Sandstone Orange"
                      - option "Sapphire Blue"
                      - option "Sea"
                      - option "Sierra Blue"
                      - option "Silver"
                      - option "Silver Shadow"
                      - option "Sky Blue"
                      - option "Smoke Blue"
                      - option "Snow"
                      - option "Sorta Sage"
                      - option "Sorta Seafoam"
                      - option "Sorta Sunny"
                      - option "Space Black"
                      - option "Space Gray"
                      - option "Spacegray"
                      - option "Starlight"
                      - option "Stormy Black"
                      - option "Sunny"
                      - option "Tangerine"
                      - option "Tea Green"
                      - option "Teal"
                      - option "Thom Browne Edition"
                      - option "Titanium"
                      - option "Titanium Black"
                      - option "Titanium Blue"
                      - option "Titanium Gray"
                      - option "Titanium Green"
                      - option "Titanium Icyblue"
                      - option "Titanium Jadegreen"
                      - option "Titanium Jetblack"
                      - option "Titanium Orange"
                      - option "Titanium Pinkgold"
                      - option "Titanium Silver"
                      - option "Titanium Silverblue"
                      - option "Titanium Violet"
                      - option "Titanium Whitesilver"
                      - option "Titanium Yellow"
                      - option "Ultramarine"
                      - option "Violet"
                      - option "White"
                      - option "White Blue"
                      - option "White Titanium"
                      - option "Wintergreen"
                      - option "Yellow"
                  - columnheader "All" [ref=e129]:
                    - combobox [ref=e130] [cursor=pointer]:
                      - option "All" [selected]
                  - columnheader [ref=e131]:
                    - spinbutton [ref=e132]
                  - columnheader [ref=e133]:
                    - spinbutton [ref=e134]
              - rowgroup [ref=e135]:
                - row "PWS000000100308 $1250.00 0" [ref=e136] [cursor=pointer]:
                  - cell [ref=e137]:
                    - checkbox [ref=e138]
                  - cell "PWS000000100308" [ref=e139]
                  - cell [ref=e140]
                  - cell [ref=e141]
                  - cell [ref=e142]
                  - cell [ref=e143]
                  - cell [ref=e144]
                  - cell [ref=e145]
                  - cell [ref=e146]
                  - cell "$1250.00" [ref=e147]
                  - cell "0" [ref=e148]
                - row "PWS00000058333 Tablet Apple iPad Air 2 16GB Silver $1250.00 0" [ref=e149] [cursor=pointer]:
                  - cell [ref=e150]:
                    - checkbox [ref=e151]
                  - cell "PWS00000058333" [ref=e152]
                  - cell "Tablet" [ref=e153]
                  - cell "Apple" [ref=e154]
                  - cell "iPad Air 2" [ref=e155]
                  - cell [ref=e156]
                  - cell "16GB" [ref=e157]
                  - cell "Silver" [ref=e158]
                  - cell [ref=e159]
                  - cell "$1250.00" [ref=e160]
                  - cell "0" [ref=e161]
                - row "PWS00000058434 Tablet Apple iPad Air 2 16GB Space Gray $1250.00 0" [ref=e162] [cursor=pointer]:
                  - cell [ref=e163]:
                    - checkbox [ref=e164]
                  - cell "PWS00000058434" [ref=e165]
                  - cell "Tablet" [ref=e166]
                  - cell "Apple" [ref=e167]
                  - cell "iPad Air 2" [ref=e168]
                  - cell [ref=e169]
                  - cell "16GB" [ref=e170]
                  - cell "Space Gray" [ref=e171]
                  - cell [ref=e172]
                  - cell "$1250.00" [ref=e173]
                  - cell "0" [ref=e174]
                - row "PWS00000058470 Tablet Apple iPad Air 2 16GB Gold $1250.00 0" [ref=e175] [cursor=pointer]:
                  - cell [ref=e176]:
                    - checkbox [ref=e177]
                  - cell "PWS00000058470" [ref=e178]
                  - cell "Tablet" [ref=e179]
                  - cell "Apple" [ref=e180]
                  - cell "iPad Air 2" [ref=e181]
                  - cell [ref=e182]
                  - cell "16GB" [ref=e183]
                  - cell "Gold" [ref=e184]
                  - cell [ref=e185]
                  - cell "$1250.00" [ref=e186]
                  - cell "0" [ref=e187]
                - row "PWS00000060478 Tablet Apple iPad Air 2 128GB Gold $1250.00 0" [ref=e188] [cursor=pointer]:
                  - cell [ref=e189]:
                    - checkbox [ref=e190]
                  - cell "PWS00000060478" [ref=e191]
                  - cell "Tablet" [ref=e192]
                  - cell "Apple" [ref=e193]
                  - cell "iPad Air 2" [ref=e194]
                  - cell [ref=e195]
                  - cell "128GB" [ref=e196]
                  - cell "Gold" [ref=e197]
                  - cell [ref=e198]
                  - cell "$1250.00" [ref=e199]
                  - cell "0" [ref=e200]
                - row "PWS00000075203 Tablet Apple iPad Pro (12.9-inch) 128GB Space Gray $1250.00 0" [ref=e201] [cursor=pointer]:
                  - cell [ref=e202]:
                    - checkbox [ref=e203]
                  - cell "PWS00000075203" [ref=e204]
                  - cell "Tablet" [ref=e205]
                  - cell "Apple" [ref=e206]
                  - cell "iPad Pro (12.9-inch)" [ref=e207]
                  - cell [ref=e208]
                  - cell "128GB" [ref=e209]
                  - cell "Space Gray" [ref=e210]
                  - cell [ref=e211]
                  - cell "$1250.00" [ref=e212]
                  - cell "0" [ref=e213]
                - row "PWS00000075389 Tablet Apple iPad mini 4 128GB Gold $1250.00 0" [ref=e214] [cursor=pointer]:
                  - cell [ref=e215]:
                    - checkbox [ref=e216]
                  - cell "PWS00000075389" [ref=e217]
                  - cell "Tablet" [ref=e218]
                  - cell "Apple" [ref=e219]
                  - cell "iPad mini 4" [ref=e220]
                  - cell [ref=e221]
                  - cell "128GB" [ref=e222]
                  - cell "Gold" [ref=e223]
                  - cell [ref=e224]
                  - cell "$1250.00" [ref=e225]
                  - cell "0" [ref=e226]
                - row "PWS00000075729 Tablet Apple iPad mini 4 128GB Space Gray $1250.00 0" [ref=e227] [cursor=pointer]:
                  - cell [ref=e228]:
                    - checkbox [ref=e229]
                  - cell "PWS00000075729" [ref=e230]
                  - cell "Tablet" [ref=e231]
                  - cell "Apple" [ref=e232]
                  - cell "iPad mini 4" [ref=e233]
                  - cell [ref=e234]
                  - cell "128GB" [ref=e235]
                  - cell "Space Gray" [ref=e236]
                  - cell [ref=e237]
                  - cell "$1250.00" [ref=e238]
                  - cell "0" [ref=e239]
                - row "PWS00000077529 Tablet Apple iPad Pro (9.7-inch) 128GB Space Gray $1250.00 96" [ref=e240] [cursor=pointer]:
                  - cell [ref=e241]:
                    - checkbox [ref=e242]
                  - cell "PWS00000077529" [ref=e243]
                  - cell "Tablet" [ref=e244]
                  - cell "Apple" [ref=e245]
                  - cell "iPad Pro (9.7-inch)" [ref=e246]
                  - cell [ref=e247]
                  - cell "128GB" [ref=e248]
                  - cell "Space Gray" [ref=e249]
                  - cell [ref=e250]
                  - cell "$1250.00" [ref=e251]
                  - cell "96" [ref=e252]
                - row "PWS00000077862 Tablet Apple iPad mini 4 128GB Space Gray $1250.00 0" [ref=e253] [cursor=pointer]:
                  - cell [ref=e254]:
                    - checkbox [ref=e255]
                  - cell "PWS00000077862" [ref=e256]
                  - cell "Tablet" [ref=e257]
                  - cell "Apple" [ref=e258]
                  - cell "iPad mini 4" [ref=e259]
                  - cell [ref=e260]
                  - cell "128GB" [ref=e261]
                  - cell "Space Gray" [ref=e262]
                  - cell [ref=e263]
                  - cell "$1250.00" [ref=e264]
                  - cell "0" [ref=e265]
                - row "PWS00000078228 Tablet Apple iPad mini 4 64GB Space Gray $1250.00 99" [ref=e266] [cursor=pointer]:
                  - cell [ref=e267]:
                    - checkbox [ref=e268]
                  - cell "PWS00000078228" [ref=e269]
                  - cell "Tablet" [ref=e270]
                  - cell "Apple" [ref=e271]
                  - cell "iPad mini 4" [ref=e272]
                  - cell [ref=e273]
                  - cell "64GB" [ref=e274]
                  - cell "Space Gray" [ref=e275]
                  - cell [ref=e276]
                  - cell "$1250.00" [ref=e277]
                  - cell "99" [ref=e278]
                - row "PWS00000078536 Tablet Apple iPad Pro (9.7-inch) 32GB Rose Gold $1250.00 99" [ref=e279] [cursor=pointer]:
                  - cell [ref=e280]:
                    - checkbox [ref=e281]
                  - cell "PWS00000078536" [ref=e282]
                  - cell "Tablet" [ref=e283]
                  - cell "Apple" [ref=e284]
                  - cell "iPad Pro (9.7-inch)" [ref=e285]
                  - cell [ref=e286]
                  - cell "32GB" [ref=e287]
                  - cell "Rose Gold" [ref=e288]
                  - cell [ref=e289]
                  - cell "$1250.00" [ref=e290]
                  - cell "99" [ref=e291]
                - row "PWS00000079268 Tablet Apple iPad Pro (9.7-inch) 32GB Space Gray $1250.00 99" [ref=e292] [cursor=pointer]:
                  - cell [ref=e293]:
                    - checkbox [ref=e294]
                  - cell "PWS00000079268" [ref=e295]
                  - cell "Tablet" [ref=e296]
                  - cell "Apple" [ref=e297]
                  - cell "iPad Pro (9.7-inch)" [ref=e298]
                  - cell [ref=e299]
                  - cell "32GB" [ref=e300]
                  - cell "Space Gray" [ref=e301]
                  - cell [ref=e302]
                  - cell "$1250.00" [ref=e303]
                  - cell "99" [ref=e304]
                - row "PWS00000079281 Tablet Apple iPad Pro (9.7-inch) 256GB Gold $1250.00 0" [ref=e305] [cursor=pointer]:
                  - cell [ref=e306]:
                    - checkbox [ref=e307]
                  - cell "PWS00000079281" [ref=e308]
                  - cell "Tablet" [ref=e309]
                  - cell "Apple" [ref=e310]
                  - cell "iPad Pro (9.7-inch)" [ref=e311]
                  - cell [ref=e312]
                  - cell "256GB" [ref=e313]
                  - cell "Gold" [ref=e314]
                  - cell [ref=e315]
                  - cell "$1250.00" [ref=e316]
                  - cell "0" [ref=e317]
                - row "PWS00000079535 Tablet Apple iPad mini 4 128GB Space Gray $1250.00 99" [ref=e318] [cursor=pointer]:
                  - cell [ref=e319]:
                    - checkbox [ref=e320]
                  - cell "PWS00000079535" [ref=e321]
                  - cell "Tablet" [ref=e322]
                  - cell "Apple" [ref=e323]
                  - cell "iPad mini 4" [ref=e324]
                  - cell [ref=e325]
                  - cell "128GB" [ref=e326]
                  - cell "Space Gray" [ref=e327]
                  - cell [ref=e328]
                  - cell "$1250.00" [ref=e329]
                  - cell "99" [ref=e330]
                - row "PWS00000082348 Tablet Apple iPad mini 4 128GB Silver $1250.00 0" [ref=e331] [cursor=pointer]:
                  - cell [ref=e332]:
                    - checkbox [ref=e333]
                  - cell "PWS00000082348" [ref=e334]
                  - cell "Tablet" [ref=e335]
                  - cell "Apple" [ref=e336]
                  - cell "iPad mini 4" [ref=e337]
                  - cell [ref=e338]
                  - cell "128GB" [ref=e339]
                  - cell "Silver" [ref=e340]
                  - cell [ref=e341]
                  - cell "$1250.00" [ref=e342]
                  - cell "0" [ref=e343]
                - row "PWS00000083915 Tablet Apple iPad mini 4 128GB Silver $1250.00 80" [ref=e344] [cursor=pointer]:
                  - cell [ref=e345]:
                    - checkbox [ref=e346]
                  - cell "PWS00000083915" [ref=e347]
                  - cell "Tablet" [ref=e348]
                  - cell "Apple" [ref=e349]
                  - cell "iPad mini 4" [ref=e350]
                  - cell [ref=e351]
                  - cell "128GB" [ref=e352]
                  - cell "Silver" [ref=e353]
                  - cell [ref=e354]
                  - cell "$1250.00" [ref=e355]
                  - cell "80" [ref=e356]
                - row "PWS00000085103 Tablet Apple iPad (5th generation) 32GB Gold $1250.00 90" [ref=e357] [cursor=pointer]:
                  - cell [ref=e358]:
                    - checkbox [ref=e359]
                  - cell "PWS00000085103" [ref=e360]
                  - cell "Tablet" [ref=e361]
                  - cell "Apple" [ref=e362]
                  - cell "iPad (5th generation)" [ref=e363]
                  - cell [ref=e364]
                  - cell "32GB" [ref=e365]
                  - cell "Gold" [ref=e366]
                  - cell [ref=e367]
                  - cell "$1250.00" [ref=e368]
                  - cell "90" [ref=e369]
                - row "PWS00000085137 Tablet Apple iPad (5th generation) 32GB Space Gray $1250.00 99" [ref=e370] [cursor=pointer]:
                  - cell [ref=e371]:
                    - checkbox [ref=e372]
                  - cell "PWS00000085137" [ref=e373]
                  - cell "Tablet" [ref=e374]
                  - cell "Apple" [ref=e375]
                  - cell "iPad (5th generation)" [ref=e376]
                  - cell [ref=e377]
                  - cell "32GB" [ref=e378]
                  - cell "Space Gray" [ref=e379]
                  - cell [ref=e380]
                  - cell "$1250.00" [ref=e381]
                  - cell "99" [ref=e382]
                - row "PWS00000085148 Tablet Apple iPad Air 2 32GB Space Gray $1250.00 95" [ref=e383] [cursor=pointer]:
                  - cell [ref=e384]:
                    - checkbox [ref=e385]
                  - cell "PWS00000085148" [ref=e386]
                  - cell "Tablet" [ref=e387]
                  - cell "Apple" [ref=e388]
                  - cell "iPad Air 2" [ref=e389]
                  - cell [ref=e390]
                  - cell "32GB" [ref=e391]
                  - cell "Space Gray" [ref=e392]
                  - cell [ref=e393]
                  - cell "$1250.00" [ref=e394]
                  - cell "95" [ref=e395]
                - row "PWS00000085230 Tablet Apple iPad (5th generation) 32GB Space Gray $1250.00 95" [ref=e396] [cursor=pointer]:
                  - cell [ref=e397]:
                    - checkbox [ref=e398]
                  - cell "PWS00000085230" [ref=e399]
                  - cell "Tablet" [ref=e400]
                  - cell "Apple" [ref=e401]
                  - cell "iPad (5th generation)" [ref=e402]
                  - cell [ref=e403]
                  - cell "32GB" [ref=e404]
                  - cell "Space Gray" [ref=e405]
                  - cell [ref=e406]
                  - cell "$1250.00" [ref=e407]
                  - cell "95" [ref=e408]
                - row "PWS00000085513 Tablet Apple iPad (5th generation) 32GB Silver $1250.00 0" [ref=e409] [cursor=pointer]:
                  - cell [ref=e410]:
                    - checkbox [ref=e411]
                  - cell "PWS00000085513" [ref=e412]
                  - cell "Tablet" [ref=e413]
                  - cell "Apple" [ref=e414]
                  - cell "iPad (5th generation)" [ref=e415]
                  - cell [ref=e416]
                  - cell "32GB" [ref=e417]
                  - cell "Silver" [ref=e418]
                  - cell [ref=e419]
                  - cell "$1250.00" [ref=e420]
                  - cell "0" [ref=e421]
                - row "PWS00000085881 Tablet Apple iPad (5th generation) 32GB Gold $1250.00 10" [ref=e422] [cursor=pointer]:
                  - cell [ref=e423]:
                    - checkbox [ref=e424]
                  - cell "PWS00000085881" [ref=e425]
                  - cell "Tablet" [ref=e426]
                  - cell "Apple" [ref=e427]
                  - cell "iPad (5th generation)" [ref=e428]
                  - cell [ref=e429]
                  - cell "32GB" [ref=e430]
                  - cell "Gold" [ref=e431]
                  - cell [ref=e432]
                  - cell "$1250.00" [ref=e433]
                  - cell "10" [ref=e434]
                - row "PWS00000085900 Tablet Apple iPad (5th generation) 32GB Space Gray $1250.00 1" [ref=e435] [cursor=pointer]:
                  - cell [ref=e436]:
                    - checkbox [ref=e437]
                  - cell "PWS00000085900" [ref=e438]
                  - cell "Tablet" [ref=e439]
                  - cell "Apple" [ref=e440]
                  - cell "iPad (5th generation)" [ref=e441]
                  - cell [ref=e442]
                  - cell "32GB" [ref=e443]
                  - cell "Space Gray" [ref=e444]
                  - cell [ref=e445]
                  - cell "$1250.00" [ref=e446]
                  - cell "1" [ref=e447]
                - row "PWS00000086212 Tablet Apple iPad Pro (10.5-inch) 64GB Rose Gold $1250.00 0" [ref=e448] [cursor=pointer]:
                  - cell [ref=e449]:
                    - checkbox [ref=e450]
                  - cell "PWS00000086212" [ref=e451]
                  - cell "Tablet" [ref=e452]
                  - cell "Apple" [ref=e453]
                  - cell "iPad Pro (10.5-inch)" [ref=e454]
                  - cell [ref=e455]
                  - cell "64GB" [ref=e456]
                  - cell "Rose Gold" [ref=e457]
                  - cell [ref=e458]
                  - cell "$1250.00" [ref=e459]
                  - cell "0" [ref=e460]
                - row "PWS00000086684 Tablet Apple iPad (5th generation) 32GB Gold $1250.00 0" [ref=e461] [cursor=pointer]:
                  - cell [ref=e462]:
                    - checkbox [ref=e463]
                  - cell "PWS00000086684" [ref=e464]
                  - cell "Tablet" [ref=e465]
                  - cell "Apple" [ref=e466]
                  - cell "iPad (5th generation)" [ref=e467]
                  - cell [ref=e468]
                  - cell "32GB" [ref=e469]
                  - cell "Gold" [ref=e470]
                  - cell [ref=e471]
                  - cell "$1250.00" [ref=e472]
                  - cell "0" [ref=e473]
                - row "PWS00000086686 Tablet Apple iPad (5th generation) 32GB Gold $1250.00 2" [ref=e474] [cursor=pointer]:
                  - cell [ref=e475]:
                    - checkbox [ref=e476]
                  - cell "PWS00000086686" [ref=e477]
                  - cell "Tablet" [ref=e478]
                  - cell "Apple" [ref=e479]
                  - cell "iPad (5th generation)" [ref=e480]
                  - cell [ref=e481]
                  - cell "32GB" [ref=e482]
                  - cell "Gold" [ref=e483]
                  - cell [ref=e484]
                  - cell "$1250.00" [ref=e485]
                  - cell "2" [ref=e486]
                - row "PWS00000086689 Tablet Apple iPad (5th generation) 32GB Space Gray $1250.00 10" [ref=e487] [cursor=pointer]:
                  - cell [ref=e488]:
                    - checkbox [ref=e489]
                  - cell "PWS00000086689" [ref=e490]
                  - cell "Tablet" [ref=e491]
                  - cell "Apple" [ref=e492]
                  - cell "iPad (5th generation)" [ref=e493]
                  - cell [ref=e494]
                  - cell "32GB" [ref=e495]
                  - cell "Space Gray" [ref=e496]
                  - cell [ref=e497]
                  - cell "$1250.00" [ref=e498]
                  - cell "10" [ref=e499]
                - row "PWS00000086691 Tablet Apple iPad (5th generation) 32GB Silver $1250.00 10" [ref=e500] [cursor=pointer]:
                  - cell [ref=e501]:
                    - checkbox [ref=e502]
                  - cell "PWS00000086691" [ref=e503]
                  - cell "Tablet" [ref=e504]
                  - cell "Apple" [ref=e505]
                  - cell "iPad (5th generation)" [ref=e506]
                  - cell [ref=e507]
                  - cell "32GB" [ref=e508]
                  - cell "Silver" [ref=e509]
                  - cell [ref=e510]
                  - cell "$1250.00" [ref=e511]
                  - cell "10" [ref=e512]
                - row "PWS00000087692 Tablet $1250.00 20" [ref=e513] [cursor=pointer]:
                  - cell [ref=e514]:
                    - checkbox [ref=e515]
                  - cell "PWS00000087692" [ref=e516]
                  - cell "Tablet" [ref=e517]
                  - cell [ref=e518]
                  - cell [ref=e519]
                  - cell [ref=e520]
                  - cell [ref=e521]
                  - cell [ref=e522]
                  - cell [ref=e523]
                  - cell "$1250.00" [ref=e524]
                  - cell "20" [ref=e525]
                - row "PWS00000088556 Tablet Apple iPad mini 4 32GB Gold $1250.00 0" [ref=e526] [cursor=pointer]:
                  - cell [ref=e527]:
                    - checkbox [ref=e528]
                  - cell "PWS00000088556" [ref=e529]
                  - cell "Tablet" [ref=e530]
                  - cell "Apple" [ref=e531]
                  - cell "iPad mini 4" [ref=e532]
                  - cell [ref=e533]
                  - cell "32GB" [ref=e534]
                  - cell "Gold" [ref=e535]
                  - cell [ref=e536]
                  - cell "$1250.00" [ref=e537]
                  - cell "0" [ref=e538]
                - row "PWS00000088570 Tablet Apple iPad Pro (10.5-inch) 256GB Rose Gold $1250.00 0" [ref=e539] [cursor=pointer]:
                  - cell [ref=e540]:
                    - checkbox [ref=e541]
                  - cell "PWS00000088570" [ref=e542]
                  - cell "Tablet" [ref=e543]
                  - cell "Apple" [ref=e544]
                  - cell "iPad Pro (10.5-inch)" [ref=e545]
                  - cell [ref=e546]
                  - cell "256GB" [ref=e547]
                  - cell "Rose Gold" [ref=e548]
                  - cell [ref=e549]
                  - cell "$1250.00" [ref=e550]
                  - cell "0" [ref=e551]
                - row "PWS00000089209 Tablet Apple iPad (6th generation) 32GB Space Gray $1250.00 0" [ref=e552] [cursor=pointer]:
                  - cell [ref=e553]:
                    - checkbox [ref=e554]
                  - cell "PWS00000089209" [ref=e555]
                  - cell "Tablet" [ref=e556]
                  - cell "Apple" [ref=e557]
                  - cell "iPad (6th generation)" [ref=e558]
                  - cell [ref=e559]
                  - cell "32GB" [ref=e560]
                  - cell "Space Gray" [ref=e561]
                  - cell [ref=e562]
                  - cell "$1250.00" [ref=e563]
                  - cell "0" [ref=e564]
                - row "PWS00000089213 Tablet Apple iPad (6th generation) 128GB Space Gray $1250.00 2" [ref=e565] [cursor=pointer]:
                  - cell [ref=e566]:
                    - checkbox [ref=e567]
                  - cell "PWS00000089213" [ref=e568]
                  - cell "Tablet" [ref=e569]
                  - cell "Apple" [ref=e570]
                  - cell "iPad (6th generation)" [ref=e571]
                  - cell [ref=e572]
                  - cell "128GB" [ref=e573]
                  - cell "Space Gray" [ref=e574]
                  - cell [ref=e575]
                  - cell "$1250.00" [ref=e576]
                  - cell "2" [ref=e577]
                - row "PWS00000089325 Tablet Apple iPad (6th generation) 32GB Gold $1250.00 8" [ref=e578] [cursor=pointer]:
                  - cell [ref=e579]:
                    - checkbox [ref=e580]
                  - cell "PWS00000089325" [ref=e581]
                  - cell "Tablet" [ref=e582]
                  - cell "Apple" [ref=e583]
                  - cell "iPad (6th generation)" [ref=e584]
                  - cell [ref=e585]
                  - cell "32GB" [ref=e586]
                  - cell "Gold" [ref=e587]
                  - cell [ref=e588]
                  - cell "$1250.00" [ref=e589]
                  - cell "8" [ref=e590]
                - row "PWS00000089526 Tablet Apple iPad (5th generation) 32GB Space Gray $1250.00 2" [ref=e591] [cursor=pointer]:
                  - cell [ref=e592]:
                    - checkbox [ref=e593]
                  - cell "PWS00000089526" [ref=e594]
                  - cell "Tablet" [ref=e595]
                  - cell "Apple" [ref=e596]
                  - cell "iPad (5th generation)" [ref=e597]
                  - cell [ref=e598]
                  - cell "32GB" [ref=e599]
                  - cell "Space Gray" [ref=e600]
                  - cell [ref=e601]
                  - cell "$1250.00" [ref=e602]
                  - cell "2" [ref=e603]
                - row "PWS00000089637 Tablet Apple iPad (6th generation) 128GB Space Gray $1250.00 10" [ref=e604] [cursor=pointer]:
                  - cell [ref=e605]:
                    - checkbox [ref=e606]
                  - cell "PWS00000089637" [ref=e607]
                  - cell "Tablet" [ref=e608]
                  - cell "Apple" [ref=e609]
                  - cell "iPad (6th generation)" [ref=e610]
                  - cell [ref=e611]
                  - cell "128GB" [ref=e612]
                  - cell "Space Gray" [ref=e613]
                  - cell [ref=e614]
                  - cell "$1250.00" [ref=e615]
                  - cell "10" [ref=e616]
                - row "PWS00000089708 Tablet Apple iPad (6th generation) 32GB Silver $1250.00 9" [ref=e617] [cursor=pointer]:
                  - cell [ref=e618]:
                    - checkbox [ref=e619]
                  - cell "PWS00000089708" [ref=e620]
                  - cell "Tablet" [ref=e621]
                  - cell "Apple" [ref=e622]
                  - cell "iPad (6th generation)" [ref=e623]
                  - cell [ref=e624]
                  - cell "32GB" [ref=e625]
                  - cell "Silver" [ref=e626]
                  - cell [ref=e627]
                  - cell "$1250.00" [ref=e628]
                  - cell "9" [ref=e629]
                - row "PWS00000089764 Tablet Apple iPad (5th generation) 128GB Space Gray $1250.00 10" [ref=e630] [cursor=pointer]:
                  - cell [ref=e631]:
                    - checkbox [ref=e632]
                  - cell "PWS00000089764" [ref=e633]
                  - cell "Tablet" [ref=e634]
                  - cell "Apple" [ref=e635]
                  - cell "iPad (5th generation)" [ref=e636]
                  - cell [ref=e637]
                  - cell "128GB" [ref=e638]
                  - cell "Space Gray" [ref=e639]
                  - cell [ref=e640]
                  - cell "$1250.00" [ref=e641]
                  - cell "10" [ref=e642]
                - row "PWS00000091109 Tablet Apple iPad (6th generation) 32GB Silver $1250.00 10" [ref=e643] [cursor=pointer]:
                  - cell [ref=e644]:
                    - checkbox [ref=e645]
                  - cell "PWS00000091109" [ref=e646]
                  - cell "Tablet" [ref=e647]
                  - cell "Apple" [ref=e648]
                  - cell "iPad (6th generation)" [ref=e649]
                  - cell [ref=e650]
                  - cell "32GB" [ref=e651]
                  - cell "Silver" [ref=e652]
                  - cell [ref=e653]
                  - cell "$1250.00" [ref=e654]
                  - cell "10" [ref=e655]
                - row "PWS00000091234 Tablet Apple iPad (6th generation) 128GB Silver $1250.00 0" [ref=e656] [cursor=pointer]:
                  - cell [ref=e657]:
                    - checkbox [ref=e658]
                  - cell "PWS00000091234" [ref=e659]
                  - cell "Tablet" [ref=e660]
                  - cell "Apple" [ref=e661]
                  - cell "iPad (6th generation)" [ref=e662]
                  - cell [ref=e663]
                  - cell "128GB" [ref=e664]
                  - cell "Silver" [ref=e665]
                  - cell [ref=e666]
                  - cell "$1250.00" [ref=e667]
                  - cell "0" [ref=e668]
                - row "PWS00000091318 Tablet Apple iPad Air 2 32GB Space Gray $1250.00 0" [ref=e669] [cursor=pointer]:
                  - cell [ref=e670]:
                    - checkbox [ref=e671]
                  - cell "PWS00000091318" [ref=e672]
                  - cell "Tablet" [ref=e673]
                  - cell "Apple" [ref=e674]
                  - cell "iPad Air 2" [ref=e675]
                  - cell [ref=e676]
                  - cell "32GB" [ref=e677]
                  - cell "Space Gray" [ref=e678]
                  - cell [ref=e679]
                  - cell "$1250.00" [ref=e680]
                  - cell "0" [ref=e681]
                - row "PWS00000091766 Tablet Apple iPad Air 2 32GB Space Gray $1250.00 15" [ref=e682] [cursor=pointer]:
                  - cell [ref=e683]:
                    - checkbox [ref=e684]
                  - cell "PWS00000091766" [ref=e685]
                  - cell "Tablet" [ref=e686]
                  - cell "Apple" [ref=e687]
                  - cell "iPad Air 2" [ref=e688]
                  - cell [ref=e689]
                  - cell "32GB" [ref=e690]
                  - cell "Space Gray" [ref=e691]
                  - cell [ref=e692]
                  - cell "$1250.00" [ref=e693]
                  - cell "15" [ref=e694]
                - row "PWS00000091853 Tablet Apple iPad (6th generation) 32GB Space Gray $1250.00 0" [ref=e695] [cursor=pointer]:
                  - cell [ref=e696]:
                    - checkbox [ref=e697]
                  - cell "PWS00000091853" [ref=e698]
                  - cell "Tablet" [ref=e699]
                  - cell "Apple" [ref=e700]
                  - cell "iPad (6th generation)" [ref=e701]
                  - cell [ref=e702]
                  - cell "32GB" [ref=e703]
                  - cell "Space Gray" [ref=e704]
                  - cell [ref=e705]
                  - cell "$1250.00" [ref=e706]
                  - cell "0" [ref=e707]
                - row "PWS00000091856 Tablet Apple iPad (6th generation) 32GB Gold $1250.00 7" [ref=e708] [cursor=pointer]:
                  - cell [ref=e709]:
                    - checkbox [ref=e710]
                  - cell "PWS00000091856" [ref=e711]
                  - cell "Tablet" [ref=e712]
                  - cell "Apple" [ref=e713]
                  - cell "iPad (6th generation)" [ref=e714]
                  - cell [ref=e715]
                  - cell "32GB" [ref=e716]
                  - cell "Gold" [ref=e717]
                  - cell [ref=e718]
                  - cell "$1250.00" [ref=e719]
                  - cell "7" [ref=e720]
                - row "PWS00000092168 Tablet Apple iPad Pro 11-inch 64GB Space Gray $1250.00 0" [ref=e721] [cursor=pointer]:
                  - cell [ref=e722]:
                    - checkbox [ref=e723]
                  - cell "PWS00000092168" [ref=e724]
                  - cell "Tablet" [ref=e725]
                  - cell "Apple" [ref=e726]
                  - cell "iPad Pro 11-inch" [ref=e727]
                  - cell [ref=e728]
                  - cell "64GB" [ref=e729]
                  - cell "Space Gray" [ref=e730]
                  - cell [ref=e731]
                  - cell "$1250.00" [ref=e732]
                  - cell "0" [ref=e733]
                - row "PWS00000092848 Tablet Apple iPad Pro 11-inch 64GB Silver $1250.00 9977" [ref=e734] [cursor=pointer]:
                  - cell [ref=e735]:
                    - checkbox [ref=e736]
                  - cell "PWS00000092848" [ref=e737]
                  - cell "Tablet" [ref=e738]
                  - cell "Apple" [ref=e739]
                  - cell "iPad Pro 11-inch" [ref=e740]
                  - cell [ref=e741]
                  - cell "64GB" [ref=e742]
                  - cell "Silver" [ref=e743]
                  - cell [ref=e744]
                  - cell "$1250.00" [ref=e745]
                  - cell "9977" [ref=e746]
                - row "PWS00000093803 Tablet Apple iPad Pro 11-inch 512GB Silver $1250.00 0" [ref=e747] [cursor=pointer]:
                  - cell [ref=e748]:
                    - checkbox [ref=e749]
                  - cell "PWS00000093803" [ref=e750]
                  - cell "Tablet" [ref=e751]
                  - cell "Apple" [ref=e752]
                  - cell "iPad Pro 11-inch" [ref=e753]
                  - cell [ref=e754]
                  - cell "512GB" [ref=e755]
                  - cell "Silver" [ref=e756]
                  - cell [ref=e757]
                  - cell "$1250.00" [ref=e758]
                  - cell "0" [ref=e759]
                - row "PWS00000094052 Tablet Apple iPad Pro 11-inch 256GB Silver $1250.00 0" [ref=e760] [cursor=pointer]:
                  - cell [ref=e761]:
                    - checkbox [ref=e762]
                  - cell "PWS00000094052" [ref=e763]
                  - cell "Tablet" [ref=e764]
                  - cell "Apple" [ref=e765]
                  - cell "iPad Pro 11-inch" [ref=e766]
                  - cell [ref=e767]
                  - cell "256GB" [ref=e768]
                  - cell "Silver" [ref=e769]
                  - cell [ref=e770]
                  - cell "$1250.00" [ref=e771]
                  - cell "0" [ref=e772]
                - row "PWS00000094154 Tablet Apple iPad Pro 11-inch 64GB Space Gray $1250.00 0" [ref=e773] [cursor=pointer]:
                  - cell [ref=e774]:
                    - checkbox [ref=e775]
                  - cell "PWS00000094154" [ref=e776]
                  - cell "Tablet" [ref=e777]
                  - cell "Apple" [ref=e778]
                  - cell "iPad Pro 11-inch" [ref=e779]
                  - cell [ref=e780]
                  - cell "64GB" [ref=e781]
                  - cell "Space Gray" [ref=e782]
                  - cell [ref=e783]
                  - cell "$1250.00" [ref=e784]
                  - cell "0" [ref=e785]
            - generic [ref=e786]:
              - button [disabled] [ref=e787]:
                - img [ref=e788]
              - button [disabled] [ref=e791]:
                - img [ref=e792]
              - generic [ref=e794]: 1 – 50 of 22445
              - button [ref=e795] [cursor=pointer]:
                - img [ref=e796]
              - button [ref=e798] [cursor=pointer]:
                - img [ref=e799]
  - alert [ref=e82]