#!/usr/bin/env python3
"""
Extracts ecoatm_eb data from a Mendix source database and emits
V75__data_auctions_reserve_bid.sql. Mirrors extract_qa_data.py CLI + FK-remap pattern.
"""
import argparse
import os
import subprocess
import sys
from pathlib import Path

import psycopg2

DB_HOSTS = {
    "qa-0327": "localhost",
    "prod-0325": "localhost",
}

OUT_PATH = Path(__file__).parent.parent / "backend/src/main/resources/db/migration/V75__data_auctions_reserve_bid.sql"


def connect(db_name: str):
    return psycopg2.connect(
        host=DB_HOSTS[db_name],
        dbname=db_name,
        user="postgres",
        password=os.environ["PGPASSWORD"],
    )


def sql_literal(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return str(v)
    # Encode to ASCII replacing non-ASCII chars to avoid encoding issues in SQL files
    s = str(v).replace("'", "''")
    s = s.encode("ascii", errors="replace").decode("ascii")
    return "'" + s + "'"


def extract_reserve_bids(conn):
    with conn.cursor() as cur:
        # Deduplicate on (productid, grade) — keep the row with the latest changeddate
        # (2 known duplicates in qa-0327 data)
        cur.execute("""
            SELECT DISTINCT ON (productid, grade)
                   id, productid, grade, brand, model, bid,
                   lastupdatedatetime, lastawardedminprice,
                   lastawardedweek, bidvalidweekdate,
                   createddate, changeddate
            FROM "ecoatm_eb$reservebid"
            ORDER BY productid, grade, changeddate DESC NULLS LAST, id DESC
        """)
        return cur.fetchall()


def extract_audit(conn):
    with conn.cursor() as cur:
        cur.execute("""
            SELECT a.id, a.oldprice, a.newprice, a.createddate, a.changeddate,
                   j."ecoatm_eb$reservebidid"
            FROM "ecoatm_eb$reservedbidaudit" a
            LEFT JOIN "ecoatm_eb$reservedbidaudit_reservebid" j
              ON j."ecoatm_eb$reservedbidauditid" = a.id
            ORDER BY a.id
        """)
        return cur.fetchall()


def extract_sync(conn):
    with conn.cursor() as cur:
        cur.execute("""
            SELECT id, lastsyncdatetime, createddate, changeddate
            FROM "ecoatm_eb$reservebidsync" LIMIT 1
        """)
        return cur.fetchone()


def sql_coalesce_ts(v):
    """Return a TIMESTAMPTZ literal, falling back to NOW() for NULL values."""
    if v is None:
        return "NOW()"
    return sql_literal(v)


def emit_sql(reserve_bids, audit, sync):
    lines = [
        "-- =============================================================================",
        "-- V75: auctions — reserve_bid data load (GENERATED by extract_eb_data.py)",
        "-- =============================================================================",
        "",
        "-- reserve_bid rows — legacy_id preserved for FK remap",
        "INSERT INTO auctions.reserve_bid (legacy_id, product_id, grade, brand, model, bid, last_update_datetime, last_awarded_min_price, last_awarded_week, bid_valid_week_date, created_date, changed_date) VALUES",
    ]
    rb_vals = []
    for rb in reserve_bids:
        (rid, productid, grade, brand, model, bid,
         lut, lawmp, law, bvwd, cd, chd) = rb
        rb_vals.append(
            f"({rid}, {sql_literal(str(productid) if productid is not None else None)}, "
            f"{sql_literal(grade)}, {sql_literal(brand)}, {sql_literal(model)}, "
            f"{sql_literal(bid)}, {sql_coalesce_ts(lut)}, {sql_literal(lawmp)}, "
            f"{sql_literal(law)}, {sql_literal(bvwd)}, "
            f"{sql_coalesce_ts(cd)}, {sql_coalesce_ts(chd)})"
        )
    lines.append(",\n".join(rb_vals) + ";")
    lines.append("")

    if audit:
        lines.append("-- reserve_bid_audit rows — reserve_bid_id remapped via legacy_id lookup")
        lines.append("INSERT INTO auctions.reserve_bid_audit (legacy_id, reserve_bid_id, old_price, new_price, created_date, changed_date)")
        lines.append("SELECT v.legacy_id, rb.id, v.old_price, v.new_price, v.created_date, v.changed_date")
        lines.append("FROM (VALUES")
        audit_vals = []
        first = True
        for a in audit:
            aid, op, np, cd, chd, legacy_rb_id = a
            if legacy_rb_id is None:
                continue  # skip orphaned audit rows with no FK
            cd_val = f"'{cd}'" if cd is not None else "NOW()"
            chd_val = f"'{chd}'" if chd is not None else "NOW()"
            if first:
                # First row: explicit casts so Postgres knows the column types
                audit_vals.append(
                    f"({aid}::bigint, {legacy_rb_id}::bigint, "
                    f"{sql_literal(op)}::numeric, {sql_literal(np)}::numeric, "
                    f"{cd_val}::timestamptz, {chd_val}::timestamptz)"
                )
                first = False
            else:
                audit_vals.append(
                    f"({aid}, {legacy_rb_id}, "
                    f"{sql_literal(op)}, {sql_literal(np)}, "
                    f"{cd_val}, {chd_val})"
                )
        lines.append(",\n".join(audit_vals))
        lines.append(") AS v(legacy_id, legacy_rb_id, old_price, new_price, created_date, changed_date)")
        lines.append("JOIN auctions.reserve_bid rb ON rb.legacy_id = v.legacy_rb_id;")
        lines.append("")

    if sync:
        sid, lsd, cd, chd = sync
        lines.append("-- reserve_bid_sync singleton (replace the V74 seed row)")
        lines.append("DELETE FROM auctions.reserve_bid_sync;")
        lines.append(
            f"INSERT INTO auctions.reserve_bid_sync (legacy_id, last_sync_datetime, created_date, changed_date) "
            f"VALUES ({sid}, {sql_coalesce_ts(lsd)}, {sql_coalesce_ts(cd)}, {sql_coalesce_ts(chd)});"
        )
        lines.append("")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-db", required=True, choices=DB_HOSTS.keys())
    args = parser.parse_args()

    with connect(args.source_db) as conn:
        rb = extract_reserve_bids(conn)
        audit = extract_audit(conn)
        sync = extract_sync(conn)

    OUT_PATH.write_text(emit_sql(rb, audit, sync), encoding="utf-8")
    print(f"Wrote {len(rb)} reserve_bid + {len(audit)} audit + "
          f"{1 if sync else 0} sync rows to {OUT_PATH}")


if __name__ == "__main__":
    sys.exit(main())
